# Generated by Django 4.2 on 2024-11-30 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioAPP', '0003_paciente_delete_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateField()),
                ('diagnostico_consulta', models.TextField()),
                ('tratamiento', models.TextField()),
                ('doctor_consulta', models.CharField(max_length=100)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='inventarioAPP.paciente')),
            ],
        ),
    ]
