# Generated by Django 4.2.16 on 2024-11-30 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarioAPP', '0004_consulta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='fecha_nacimiento',
            new_name='fecha',
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
    ]
